CRAWL_BASE_URL = "https://adm.pickxum.com/data/profile/"
CRAWL_DATA_PATH = "/home/middlek/Desktop/mnt/sdb/picxum_profile_images_2"
VECTOR_DB_URL = "http://localhost:6333"
VECTOR_DB_COLLECTION = "picsum_profile"
N8N_SUMMARIZE_PROMPT_URL = "http://localhost:5678/webhook-test/31049a8a-93fc-40d8-bd6c-c19e12f0a201"